[package]
name = "lab4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
winit = "0.28.7"
softbuffer = "0.3.2"
rand = "0.8.5"